# Copyright 2025 NVIDIA CORPORATION
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
data:
  config.yaml: |
    actions: allocate, consolidation, reclaim, preempt, stalegangeviction
    tiers:
      - plugins:
          - name: predicates
          - name: proportion
          - name: priority
          - name: nodeavailability
          - name: resourcetype
          - name: podaffinity
          - name: elastic
          - name: kubeflow
          - name: ray
          - name: taskorder
          - name: nominatednode
          - name: dynamicresources
          - name: gpupack
          - name: gpusharingorder
          - name: nodeplacement
            arguments:
              cpu: {{ .Values.scheduler.placementStrategy }}
              gpu: {{ .Values.scheduler.placementStrategy }}
kind: ConfigMap
metadata:
  labels:
    app: scheduler
  name: scheduler-config